name: Megan AI (ChatGPT)
version: 1.0.1
slug: megan_ai
description: Megan AI assistant powered by ChatGPT
arch:
  - amd64
startup: services
boot: auto
webui: http://[HOST]:[PORT:8000]
ports:
  8000/tcp: 8000
map:
  - config:rw
options: {}
schema: {}
