name: Megan AI (ChatGPT)
version: "1.0.0"
slug: megan_ai
description: Casual AI home assistant powered by ChatGPT API
arch:
  - amd64
startup: services
boot: auto
ports:
  8000/tcp: 8000
options:
  OPENAI_API_KEY: ""
  OPENAI_MODEL: "gpt-4o-mini"
schema:
  OPENAI_API_KEY: str
  OPENAI_MODEL: str
