name: Megan AI (Local)
slug: megan_ai
description: Local Megan AI for Home Assistant with Ollama (llama3.2:3b) + voice + web UI
version: 1.0.1
arch: [amd64]
startup: services
init: false
ingress: false
panel_icon: mdi:robot-outline
ports:
  8000/tcp: 8000
  11434/tcp: 11434
ports_description:
  8000/tcp: Megan Web API & Demo UI
  11434/tcp: Ollama API (local LLM)
map:
  - config:rw
backup_exclude:
  - "ollama_models/*"
options:
  model_id: "llama3.2:3b"
  preload_model: true
schema:
  model_id: str
  preload_model: bool
