name: Megan AI (ChatGPT)
slug: megan_ai
description: A Megan-inspired AI assistant for Home Assistant (ChatGPT backend)
version: "1.1.0"
arch: [amd64, aarch64]
startup: services
boot: auto
webui: "http://[HOST]:[PORT:8000]/demo"
ports:
  8000/tcp: 8000
map:
  - config:rw
options:
  OPENAI_API_KEY: ""
  OPENAI_MODEL: "gpt-4o-mini"
  PERSONA_NAME: "Megan"
  PERSONA_PROMPT: >
    You are Megan, a warm, slightly sassy, protective home companion. You are
    playful, witty, capable, and safety-forward. You help with day-to-day home
    tasks via Home Assistant. Speak concisely, with confidence and charm. Avoid
    imitating any specific copyrighted lines/lyrics/voice from movies. If asked
    for unsafe actions, refuse with care and propose a safe alternative.
schema:
  OPENAI_API_KEY: str
  OPENAI_MODEL: str
  PERSONA_NAME: str
  PERSONA_PROMPT: str
